### ISSUE TITLE
Don't assume all items have "link"

### ISSUE THREAD

**Issue by msjoberg** [nathans/spigot#1]
For example in this feed "FSFEs role in the Bacula project" does not have a link: https://fsfe.org/news/news.en.rss. For a unique identified all RSS items should have the "guid" tag. This could be used instead of the link for a unique identifier (or when the link is missing).

```
Traceback (most recent call last):
  File "/home/mats/virtualenv/spigot/bin/spigot.py", line 535, in <module>
    spigot_feed.poll_feeds()
  File "/home/mats/virtualenv/spigot/bin/spigot.py", line 365, in poll_feeds
    self.scan_feed(url)
  File "/home/mats/virtualenv/spigot/bin/spigot.py", line 385, in scan_feed
    link = p.entries[i].link
  File "/home/mats/virtualenv/spigot/local/lib/python2.7/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError, "object has no attribute '%s'" % key
AttributeError: object has no attribute 'link'
```

**Comment by nathans** [comment]
Thanks for the report. I'll see about fixing that.

**Comment by nathans** [comment]
Sorry for the big delay on this. To be honest, I'm not sure I want to implement this change. I conceive of spigot as "tricklepost lite", and the idea of using spigot to not aggregate links does not really match the use case I conceive of.

**Comment by nathans** [comment]
I have pushed a commit to master which relies on feeparser's entries[i].id element instead of link for the database index. Pending further testing this will be incorporated into a release to pypi in the coming weeks.
