### ISSUE TITLE
How to migrate spigot

### ISSUE THREAD

**Issue by Ark74** [nathans/spigot#5]
I'm moving to a newer machine. How could i migrate my spigot instance without having to republish all the articles that have been published.

I tried to rsync my spigot folder, then made a pip install.
Enable cron but when i test it with spygot.py,  i get:

<pre>
Traceback (most recent call last):
  File "/usr/local/bin/spigot.py", line 537, in <module>
    spigot_post.post_items()
  File "/usr/local/bin/spigot.py", line 461, in post_items
    verifier_callback=simple_verifier)
  File "/usr/local/lib/python2.7/dist-packages/pypump/pypump.py", line 131, in __init__
    self.oauth_request()
  File "/usr/local/lib/python2.7/dist-packages/pypump/pypump.py", line 384, in oauth_request
    result = self.verifier_callback(self.construct_oauth_url())
  File "/usr/local/lib/python2.7/dist-packages/pypump/pypump.py", line 391, in construct_oauth_url
    if response.is_redirect:
AttributeError: 'Response' object has no attribute 'is_redirect'
</pre>

Any suggestion on the migration process?
Thanks in advance.

**Comment by nathans** [comment]
This is due to the credentials for spigot actually being handled by PyPump (the module used to do pump.io API calls). Those credentials are typically found in `~/.config/PyPump/credentials.json`. If you sync those to the same path, it should work without issue.

Let me know how that works.

I'll leave this issue open until I add some documentation about where various spigot configurations are stored.

**Comment by Ark74** [comment]
Hey thanks!
I haven't updated any content so spigot won't update anything, but now when i run spigot.py, it doesn't show any error.
I assume that now it is working :)
Thanks for the quick response.

**Comment by nathans** [comment]
OK, the expanded FAQ with information on how to migrate is now in master. I will be performing a release to pypi in the next week or two.

**Comment by Ark74** [comment]
Thanks! Now i can confirm it's working correctly! :+1:
